#! /bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin

mount -t proc proc /proc
mount -t sysfs sys /sys
mount -t tmpfs run /run

swapon -a

mkdir /run/log
mkdir /run/lock
mkdir /run/resolvconf
mkdir /run/dbus
mkdir -p -m 700 /run/user/1000/
chown 1000.1000 /run/user/1000

mount -o remount,rw LABEL=linuxroot

mkdir /dev/pts
mount -t devpts pts /dev/pts
mkdir /dev/shm
mount -t tmpfs shm /dev/shm

mount -a

export HOSTNAME=$(cat /etc/hostname)
hostname "$HOSTNAME"

/usr/local/sbin/udevd --daemon

cat /etc/init/modules.list."$HOSTNAME" | xargs modprobe -a -b

ip link set lo up
/etc/init/wifi_up 

alsactl restore

dbus-daemon --system --fork

pulseaudio --system -D

xdm &

